### ISSUE TITLE
Update the UI for gender selection from TextView to Spinner

### ISSUE THREAD

**Issue by ramya-4004** [ContriHUB/Hemo#2]
Give the options in a spinner for the user to pick one among the given options of gender [Create Profile section]
1. Male
2. Female
3. Other
4. Prefer not to say

**Comment by CarefoDragneel** [comment]
![WhatsApp Image 2022-10-03 at 5 44 34 PM](https://user-images.githubusercontent.com/82697634/193574310-4ca38c79-0cef-4a81-bea0-6070b72928fc.jpeg)
![WhatsApp Image 2022-10-03 at 5 42 02 PM](https://user-images.githubusercontent.com/82697634/193574327-f59a2985-1128-4a20-994b-d074b4e415a9.jpeg)

**Comment by CarefoDragneel** [comment]
I have sent a PR for this issue please check it.
